---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/canoeprofile/canoeprofile.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/78218/articles/213699/master/file/figures/canoeprofile/canoeprofile.png"
    folder_url: "/users/78218/articles/213699/master/folder/figures/canoeprofile"
